/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Principal;
export const Time = IDL.Int;
export const VehicleType = IDL.Variant({
  'ev' : IDL.Null,
  'disabled' : IDL.Null,
  'standard' : IDL.Null,
});
export const UserId = IDL.Principal;
export const SpotId = IDL.Text;
export const Booking = IDL.Record({
  'startTime' : Time,
  'vehicleType' : VehicleType,
  'endTime' : Time,
  'userId' : UserId,
  'date' : IDL.Int,
  'spotId' : SpotId,
});
export const LevelId = IDL.Text;
export const SpotStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'free' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const ParkingSpot = IDL.Record({
  'id' : SpotId,
  'status' : SpotStatus,
  'vehicleType' : VehicleType,
  'spotNumber' : IDL.Nat,
  'level' : LevelId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([BookingId], [], []),
  'createBooking' : IDL.Func([BookingId, Booking], [], []),
  'getAllBookingsBySpotAndTimeRange' : IDL.Func(
      [SpotId, Time, Time],
      [IDL.Vec(Booking)],
      [],
    ),
  'getAllSpotsByLevelIncludingOccupied' : IDL.Func(
      [LevelId],
      [IDL.Vec(ParkingSpot)],
      ['query'],
    ),
  'getAvailableSpotsByLevel' : IDL.Func(
      [LevelId],
      [IDL.Vec(ParkingSpot)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSpotOccupancyLevelStats' : IDL.Func(
      [LevelId],
      [
        IDL.Record({
          'totalSpots' : IDL.Nat,
          'occupiedSpots' : IDL.Nat,
          'availableSpots' : IDL.Nat,
          'spotsUnderMaintenance' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserBookingsRange' : IDL.Func(
      [UserId, Time, Time],
      [IDL.Vec(Booking)],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedParkingLot' : IDL.Func([], [], []),
  'setSpotToFree' : IDL.Func([SpotId], [], []),
  'setSpotToOccupied' : IDL.Func([SpotId], [], []),
  'setSpotToUnavailable' : IDL.Func([SpotId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Principal;
  const Time = IDL.Int;
  const VehicleType = IDL.Variant({
    'ev' : IDL.Null,
    'disabled' : IDL.Null,
    'standard' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const SpotId = IDL.Text;
  const Booking = IDL.Record({
    'startTime' : Time,
    'vehicleType' : VehicleType,
    'endTime' : Time,
    'userId' : UserId,
    'date' : IDL.Int,
    'spotId' : SpotId,
  });
  const LevelId = IDL.Text;
  const SpotStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'free' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const ParkingSpot = IDL.Record({
    'id' : SpotId,
    'status' : SpotStatus,
    'vehicleType' : VehicleType,
    'spotNumber' : IDL.Nat,
    'level' : LevelId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([BookingId], [], []),
    'createBooking' : IDL.Func([BookingId, Booking], [], []),
    'getAllBookingsBySpotAndTimeRange' : IDL.Func(
        [SpotId, Time, Time],
        [IDL.Vec(Booking)],
        [],
      ),
    'getAllSpotsByLevelIncludingOccupied' : IDL.Func(
        [LevelId],
        [IDL.Vec(ParkingSpot)],
        ['query'],
      ),
    'getAvailableSpotsByLevel' : IDL.Func(
        [LevelId],
        [IDL.Vec(ParkingSpot)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSpotOccupancyLevelStats' : IDL.Func(
        [LevelId],
        [
          IDL.Record({
            'totalSpots' : IDL.Nat,
            'occupiedSpots' : IDL.Nat,
            'availableSpots' : IDL.Nat,
            'spotsUnderMaintenance' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserBookingsRange' : IDL.Func(
        [UserId, Time, Time],
        [IDL.Vec(Booking)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedParkingLot' : IDL.Func([], [], []),
    'setSpotToFree' : IDL.Func([SpotId], [], []),
    'setSpotToOccupied' : IDL.Func([SpotId], [], []),
    'setSpotToUnavailable' : IDL.Func([SpotId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };