/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'startTime' : Time,
  'vehicleType' : VehicleType,
  'endTime' : Time,
  'userId' : UserId,
  'date' : bigint,
  'spotId' : SpotId,
}
export type BookingId = Principal;
export type LevelId = string;
export interface ParkingSpot {
  'id' : SpotId,
  'status' : SpotStatus,
  'vehicleType' : VehicleType,
  'spotNumber' : bigint,
  'level' : LevelId,
}
export type SpotId = string;
export type SpotStatus = { 'occupied' : null } |
  { 'free' : null } |
  { 'maintenance' : null };
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'ev' : null } |
  { 'disabled' : null } |
  { 'standard' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[BookingId], undefined>,
  'createBooking' : ActorMethod<[BookingId, Booking], undefined>,
  'getAllBookingsBySpotAndTimeRange' : ActorMethod<
    [SpotId, Time, Time],
    Array<Booking>
  >,
  'getAllSpotsByLevelIncludingOccupied' : ActorMethod<
    [LevelId],
    Array<ParkingSpot>
  >,
  'getAvailableSpotsByLevel' : ActorMethod<[LevelId], Array<ParkingSpot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSpotOccupancyLevelStats' : ActorMethod<
    [LevelId],
    {
      'totalSpots' : bigint,
      'occupiedSpots' : bigint,
      'availableSpots' : bigint,
      'spotsUnderMaintenance' : bigint,
    }
  >,
  'getUserBookingsRange' : ActorMethod<[UserId, Time, Time], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedParkingLot' : ActorMethod<[], undefined>,
  'setSpotToFree' : ActorMethod<[SpotId], undefined>,
  'setSpotToOccupied' : ActorMethod<[SpotId], undefined>,
  'setSpotToUnavailable' : ActorMethod<[SpotId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];