/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = Principal;
export type UserId = Principal;
export type Time = bigint;
export type SpotId = string;
export interface ParkingSpot {
    id: SpotId;
    status: SpotStatus;
    vehicleType: VehicleType;
    spotNumber: bigint;
    level: LevelId;
}
export type LevelId = string;
export interface Booking {
    startTime: Time;
    vehicleType: VehicleType;
    endTime: Time;
    userId: UserId;
    date: bigint;
    spotId: SpotId;
}
export interface UserProfile {
    name: string;
}
export enum SpotStatus {
    occupied = "occupied",
    free = "free",
    maintenance = "maintenance"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleType {
    ev = "ev",
    disabled = "disabled",
    standard = "standard"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: BookingId): Promise<void>;
    createBooking(bookingId: BookingId, booking: Booking): Promise<void>;
    getAllBookingsBySpotAndTimeRange(spotId: SpotId, startTime: Time, endTime: Time): Promise<Array<Booking>>;
    getAllSpotsByLevelIncludingOccupied(levelId: LevelId): Promise<Array<ParkingSpot>>;
    getAvailableSpotsByLevel(levelId: LevelId): Promise<Array<ParkingSpot>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSpotOccupancyLevelStats(levelId: LevelId): Promise<{
        totalSpots: bigint;
        occupiedSpots: bigint;
        availableSpots: bigint;
        spotsUnderMaintenance: bigint;
    }>;
    getUserBookingsRange(userId: UserId, startTime: Time, endTime: Time): Promise<Array<Booking>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedParkingLot(): Promise<void>;
    setSpotToFree(spotId: SpotId): Promise<void>;
    setSpotToOccupied(spotId: SpotId): Promise<void>;
    setSpotToUnavailable(spotId: SpotId): Promise<void>;
}
import type { Booking as _Booking, LevelId as _LevelId, ParkingSpot as _ParkingSpot, SpotId as _SpotId, SpotStatus as _SpotStatus, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: BookingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: BookingId, arg1: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, to_candid_Booking_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, to_candid_Booking_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllBookingsBySpotAndTimeRange(arg0: SpotId, arg1: Time, arg2: Time): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingsBySpotAndTimeRange(arg0, arg1, arg2);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingsBySpotAndTimeRange(arg0, arg1, arg2);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSpotsByLevelIncludingOccupied(arg0: LevelId): Promise<Array<ParkingSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpotsByLevelIncludingOccupied(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpotsByLevelIncludingOccupied(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSpotsByLevel(arg0: LevelId): Promise<Array<ParkingSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSpotsByLevel(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSpotsByLevel(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpotOccupancyLevelStats(arg0: LevelId): Promise<{
        totalSpots: bigint;
        occupiedSpots: bigint;
        availableSpots: bigint;
        spotsUnderMaintenance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpotOccupancyLevelStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpotOccupancyLevelStats(arg0);
            return result;
        }
    }
    async getUserBookingsRange(arg0: UserId, arg1: Time, arg2: Time): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookingsRange(arg0, arg1, arg2);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookingsRange(arg0, arg1, arg2);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedParkingLot(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedParkingLot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedParkingLot();
            return result;
        }
    }
    async setSpotToFree(arg0: SpotId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSpotToFree(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSpotToFree(arg0);
            return result;
        }
    }
    async setSpotToOccupied(arg0: SpotId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSpotToOccupied(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSpotToOccupied(arg0);
            return result;
        }
    }
    async setSpotToUnavailable(arg0: SpotId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSpotToUnavailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSpotToUnavailable(arg0);
            return result;
        }
    }
}
function from_candid_Booking_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ParkingSpot_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParkingSpot): ParkingSpot {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SpotStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpotStatus): SpotStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SpotId;
    status: _SpotStatus;
    vehicleType: _VehicleType;
    spotNumber: bigint;
    level: _LevelId;
}): {
    id: SpotId;
    status: SpotStatus;
    vehicleType: VehicleType;
    spotNumber: bigint;
    level: LevelId;
} {
    return {
        id: value.id,
        status: from_candid_SpotStatus_n15(_uploadFile, _downloadFile, value.status),
        vehicleType: from_candid_VehicleType_n10(_uploadFile, _downloadFile, value.vehicleType),
        spotNumber: value.spotNumber,
        level: value.level
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: _Time;
    vehicleType: _VehicleType;
    endTime: _Time;
    userId: _UserId;
    date: bigint;
    spotId: _SpotId;
}): {
    startTime: Time;
    vehicleType: VehicleType;
    endTime: Time;
    userId: UserId;
    date: bigint;
    spotId: SpotId;
} {
    return {
        startTime: value.startTime,
        vehicleType: from_candid_VehicleType_n10(_uploadFile, _downloadFile, value.vehicleType),
        endTime: value.endTime,
        userId: value.userId,
        date: value.date,
        spotId: value.spotId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ev: null;
} | {
    disabled: null;
} | {
    standard: null;
}): VehicleType {
    return "ev" in value ? VehicleType.ev : "disabled" in value ? VehicleType.disabled : "standard" in value ? VehicleType.standard : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    free: null;
} | {
    maintenance: null;
}): SpotStatus {
    return "occupied" in value ? SpotStatus.occupied : "free" in value ? SpotStatus.free : "maintenance" in value ? SpotStatus.maintenance : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ParkingSpot>): Array<ParkingSpot> {
    return value.map((x)=>from_candid_ParkingSpot_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Booking_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Time;
    vehicleType: VehicleType;
    endTime: Time;
    userId: UserId;
    date: bigint;
    spotId: SpotId;
}): {
    startTime: _Time;
    vehicleType: _VehicleType;
    endTime: _Time;
    userId: _UserId;
    date: bigint;
    spotId: _SpotId;
} {
    return {
        startTime: value.startTime,
        vehicleType: to_candid_VehicleType_n5(_uploadFile, _downloadFile, value.vehicleType),
        endTime: value.endTime,
        userId: value.userId,
        date: value.date,
        spotId: value.spotId
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    ev: null;
} | {
    disabled: null;
} | {
    standard: null;
} {
    return value == VehicleType.ev ? {
        ev: null
    } : value == VehicleType.disabled ? {
        disabled: null
    } : value == VehicleType.standard ? {
        standard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
